version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-app}_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Symfony API
  api:
    container_name: ${COMPOSE_PROJECT_NAME:-app}_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/var/www/api
      - api_vendor:/var/www/api/vendor
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-ChangeThisSecretInProduction}
      DATABASE_URL: ${DATABASE_URL:-postgresql://app_user:app_password@postgres:5432/app_db?serverVersion=15&charset=utf8}
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  # React Frontend
  web:
    container_name: ${COMPOSE_PROJECT_NAME:-app}_web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME:-app}_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        ENV: dev
    ports:
      - "${NGINX_PORT:-80}:80"
    networks:
      - app-network
    depends_on:
      - api
      - web

volumes:
  postgres_data:
  api_vendor:
  web_node_modules:

networks:
  app-network:
    driver: bridge
