version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-app}_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Symfony API
  api:
    container_name: ${COMPOSE_PROJECT_NAME:-app}_api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # React Frontend (built into nginx)
  web:
    container_name: ${COMPOSE_PROJECT_NAME:-app}_web
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME:-app}_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        ENV: prod
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      # Mount built React app from web container
      - web_dist:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - api
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  web_dist:

networks:
  app-network:
    driver: bridge
